### ISSUE TITLE
Switch Object Handle Error

### ISSUE THREAD

**Issue by unisharpUO** [loop-uc-ui/uus-corp-ui#50]
Action: Switch Object Handle
Problem: Action does not bring up the menu for switching object handles.

Debug window output:

`[UiLog][Error]: Error executing Lua buffer ScriptCommand: [string "Data/Interface/Default/Source/Actions.lua"]: 1286: 'for' limit must be a number.`

**Comment by loop-uc-ui** [comment]
thank you @unisharpUO  fixed with #7
